[tool.pylint.messages_contol]
disable = [
    "missing-function-docstring",
    "missing-new-line",
    "missing-class-docstring",
    "missing-module-docstring",
    "invalid-name",
    "too-few-public-methods",
    "line-too-long",
    "unused-argument",
    "unused-variable",
    "missing-timeout",
]

[tool.black]
line-length = 88
skip-string-normalization = true